# Generated by Django 4.1.7 on 2023-02-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='namejob',
            field=models.TextField(max_length=20),
        ),
    ]
