# Generated by Django 4.1.7 on 2023-02-25 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_alter_jobtitle_description_alter_jobtitle_namejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtitle',
            name='posttime',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='namejob',
            field=models.TextField(max_length=60),
        ),
    ]
