# Generated by Django 4.1.7 on 2023-03-02 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_jobtitle_posttime_alter_jobtitle_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
